import React, { useEffect } from 'react'
import NavBar from '../components/NavBar'
import HeroSection from '../components/HeroSection'
import { Footer } from '../components/Footer'

export const PrivacyPolicy = () => {

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <>

    <NavBar />
    <HeroSection title = {'Privacy Policy'} displayBanner = {true} displayDownload = {false} />
    <div className="container-xxl py-5">
        <div className="container py-5 px-lg-5">
          <div className="text-center" data-wow-delay="0.1s"></div>
          <div className="row justify-content-center">
            <div className="col-lg-9">
              <div className="" data-wow-delay="0.3s">
                <p className="mb-4" style={{textAlign:"justify"}}>
                  Renambl Technologies Private Limited own and/ or operate the
                  website and mobile application yahvipay.com (“Website”, “Our
                  Website”, “Site”).
                  <br />
                  <br />
                  For the purpose of providing the Services (as defined in
                  clause 1 below), YahviPay is required to collect and use
                  certain information of the users of the Website (“Users”)
                  using the Services and involves capturing, storage and
                  transmission of such information. This privacy policy
                  ("Privacy Policy"/ “Policy”) explains how We collect, use,
                  share and protect personal information of the Users of the
                  Services (jointly and severally referred to as “You”, “Your”,
                  “Yourself” or “User” or “Users” in this Privacy Policy). We
                  have created this Privacy Policy to ensure our steady
                  commitment to the privacy of the information of the Users who
                  interact with our Services. Your use of and access to the
                  Services is subject to this Privacy Policy and our Terms and
                  Conditions. Any capitalized term used, but not defined, in
                  this Privacy Policy shall have the meaning attributed to it in
                  our Terms and Conditions.
                  <br />
                  <br />
                  The headings used herein are only for the purpose of arranging
                  the various provisions of the Privacy Policy. The headings are
                  for the purpose of reference only and shall not be interpreted
                  to limit or expand the provisions of the clauses contained
                  therein.
                </p>
              </div>
            </div>
            <div className="col-lg-9">
              <div className="" data-wow-delay="0.3s">
                <h2 className="mb-4">GENERAL</h2>
                <p className="mb-4" style={{textAlign:"justify"}}>
                  The User unequivocally agrees that this Policy and the
                  aforementioned Terms and Conditions constitute a legally
                  binding agreement between the User and YahviPay, and that the
                  User shall be subject to the rules, guidelines, policies,
                  terms, and conditions applicable to any service that is
                  provided by YahviPay including the Services, and that the same
                  shall be deemed to be incorporated into the Terms and
                  Conditions, and shall be treated as part of the same.<br />
                  This document is an electronic record in terms of Information
                  Technology Act, 2000 and rules there under as applicable and
                  the amended provisions pertaining to electronic records in
                  various statutes as amended by the Information Technology Act,
                  2000. This electronic record is generated by a computer system
                  and does not require any physical or digital signatures.
                  Further, this document is published in accordance with the
                  provisions of the SPI Rules and Intermediaries Guidelines.
                  <br />
                  <br />
                  The terms ‘Party’ and ‘Parties’ shall respectively be used to
                  refer to the User and YahviPay individually and collectively,
                  as the context so requires.
                  <br />
                  <br />
                  The headings of each section in this Policy are only for the
                  purpose of organizing the various provisions under this Policy
                  in an orderly manner and shall not be used by either Party to
                  interpret the provisions contained herein in any manner.
                  Further, it is specifically agreed to by the Parties that the
                  headings shall have no legal or contractual value.
                  <br />
                  <br />
                  The Parties expressly agree that subject to clause 13 of this
                  Policy, YahviPay retains the sole and exclusive right to amend
                  or modify the Policy and the aforementioned Terms and
                  Conditions without any prior permission or intimation to the
                  User keeping in mind best practices and laws set by
                  State/Central Government of India, and the User expressly
                  agrees that any such amendments or modifications shall come
                  into effect immediately. The User has a duty to periodically
                  check the Policy and Terms and Conditions and stay updated on
                  their provisions and requirements. If the User continues to
                  use the Services following such a change, the User will be
                  deemed to have consented to any and all amendments/
                  modifications made to the Policy and Terms and Conditions. In
                  so far as the User complies with the Policy and Terms and
                  Conditions, he/she is granted a personal, non-exclusive,
                  non-transferable, revocable, limited privilege to enter,
                  access and use the Services.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}
